  GNU nano 6.2                                                                                         nginx.conf                                                                                                  
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige toutes les routes vers index.html (pour React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}

